export const MARCAS_FIPE = [
  { codigo: '1', nome: 'Acura' },
  { codigo: '2', nome: 'Agrale' },
  { codigo: '3', nome: 'Alfa Romeo' },
  { codigo: '4', nome: 'AM Gen' },
  { codigo: '5', nome: 'Asia Motors' },
  { codigo: '6', nome: 'Aston Martin' },
  { codigo: '7', nome: 'Audi' },
  { codigo: '8', nome: 'BMW' },
  { codigo: '9', nome: 'BRM' },
  { codigo: '10', nome: 'Buggy' },
  { codigo: '11', nome: 'Bugre' },
  { codigo: '12', nome: 'Cadillac' },
  { codigo: '13', nome: 'CBT Jipe' },
  { codigo: '14', nome: 'Chery' },
  { codigo: '15', nome: 'Chevrolet' },
  { codigo: '16', nome: 'Chrysler' },
  { codigo: '17', nome: 'Citroën' },
  { codigo: '18', nome: 'Cross Lander' },
  { codigo: '19', nome: 'Daewoo' },
  { codigo: '20', nome: 'Daihatsu' },
  { codigo: '21', nome: 'Dodge' },
  { codigo: '22', nome: 'Effa' },
  { codigo: '23', nome: 'Emis' },
  { codigo: '24', nome: 'Engesa' },
  { codigo: '25', nome: 'Envemo' },
  { codigo: '26', nome: 'Ferrari' },
  { codigo: '27', nome: 'Fiat' },
  { codigo: '28', nome: 'Fibravan' },
  { codigo: '29', nome: 'Ford' },
  { codigo: '30', nome: 'Fyber' },
  { codigo: '31', nome: 'Geely' },
  { codigo: '32', nome: 'GM' },
  { codigo: '33', nome: 'Gurgel' },
  { codigo: '34', nome: 'GWM' },
  { codigo: '35', nome: 'Honda' },
  { codigo: '36', nome: 'Hyundai' },
  { codigo: '37', nome: 'Isuzu' },
  { codigo: '38', nome: 'JAC' },
  { codigo: '39', nome: 'Jaguar' },
  { codigo: '40', nome: 'Jeep' },
  { codigo: '41', nome: 'Kia' },
  { codigo: '42', nome: 'Lada' },
  { codigo: '43', nome: 'Lamborghini' },
  { codigo: '44', nome: 'Land Rover' },
  { codigo: '45', nome: 'Lexus' },
  { codigo: '46', nome: 'Lifan' },
  { codigo: '47', nome: 'Mahindra' },
  { codigo: '48', nome: 'Maserati' },
  { codigo: '49', nome: 'Mazda' },
  { codigo: '50', nome: 'Mercedes-Benz' },
  { codigo: '51', nome: 'Mitsubishi' },
  { codigo: '52', nome: 'Nissan' },
  { codigo: '53', nome: 'Peugeot' },
  { codigo: '54', nome: 'Pontiac' },
  { codigo: '55', nome: 'Porsche' },
  { codigo: '56', nome: 'RAM' },
  { codigo: '57', nome: 'Renault' },
  { codigo: '58', nome: 'Rolls-Royce' },
  { codigo: '59', nome: 'Seat' },
  { codigo: '60', nome: 'Subaru' },
  { codigo: '61', nome: 'Suzuki' },
  { codigo: '62', nome: 'Toyota' },
  { codigo: '63', nome: 'Troller' },
  { codigo: '64', nome: 'Volkswagen' },
  { codigo: '65', nome: 'Volvo' },
];

export const MODELOS_POR_MARCA = {
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron'],
  'BMW': ['116i', '118i', '120i', '125i', '130i', 'M2', 'M3', 'M4', '320i', '328i', '330i', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'iX'],
  'Chevrolet': ['Onix', 'Onix Plus', 'Tracker', 'Cruze', 'Equinox', 'Blazer', 'S10', 'Montana', 'Spin', 'Cobalt', 'Prisma', 'Celta', 'Corsa', 'Vectra', 'Captiva', 'Trailblazer', 'Traverse', 'Silverado'],
  'Citroën': ['C3', 'C4', 'C4 Cactus', 'C5 Aircross', 'Aircross', 'Berlingo', 'Jumpy', 'C3 Aircross'],
  'Fiat': ['Argo', 'Cronos', 'Pulse', 'Fastback', 'Strada', 'Toro', 'Ducato', 'Mobi', 'Uno', 'Palio', 'Siena', 'Bravo', 'Linea', 'Doblò', 'Freemont', '500'],
  'Ford': ['Ka', 'EcoSport', 'Ranger', 'Territory', 'Bronco Sport', 'Maverick', 'Edge', 'Explorer', 'F-150', 'Mustang', 'Fusion', 'Focus', 'Fiesta', 'Transit'],
  'Honda': ['Civic', 'City', 'Fit', 'HR-V', 'CR-V', 'WR-V', 'Accord', 'ZR-V', 'e:NS1', 'Pilot'],
  'Hyundai': ['HB20', 'HB20S', 'Creta', 'Tucson', 'Santa Fe', 'Sonata', 'Elantra', 'i30', 'ix35', 'Azera', 'Kona'],
  'Jeep': ['Renegade', 'Compass', 'Commander', 'Wrangler', 'Gladiator', 'Grand Cherokee', 'Cherokee'],
  'Kia': ['Sportage', 'Stinger', 'Sorento', 'Carnival', 'EV6', 'Soul', 'Cerato', 'Picanto', 'Niro', 'Telluride'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Freelander'],
  'Mercedes-Benz': ['A 180', 'A 200', 'A 250', 'C 180', 'C 200', 'C 300', 'E 200', 'E 300', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'CLA', 'AMG GT', 'EQC', 'EQS', 'Sprinter'],
  'Mitsubishi': ['ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'Pajero Sport', 'L200 Triton', 'Lancer'],
  'Nissan': ['Versa', 'Kicks', 'Frontier', 'Sentra', 'Altima', 'Leaf', 'Murano', 'Pathfinder', 'X-Trail'],
  'Peugeot': ['208', '2008', '308', '3008', '408', '508', '5008', 'Expert', 'Boxer'],
  'Porsche': ['Cayenne', 'Macan', '911', 'Panamera', 'Taycan', '718'],
  'Renault': ['Kwid', 'Sandero', 'Logan', 'Duster', 'Captur', 'Oroch', 'Jogger', 'Zoe', 'Arkana', 'Master'],
  'Toyota': ['Corolla', 'Corolla Cross', 'Yaris', 'Hilux', 'SW4', 'RAV4', 'Camry', 'Prius', 'C-HR', 'GR86', 'Land Cruiser', 'Etios'],
  'Volkswagen': ['Gol', 'Polo', 'Virtus', 'Nivus', 'T-Cross', 'Taos', 'Amarok', 'Saveiro', 'Voyage', 'Fox', 'Golf', 'Jetta', 'Tiguan', 'Touareg', 'ID.4', 'ID.6'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90', 'C40'],
  'Subaru': ['Impreza', 'Legacy', 'Forester', 'Outback', 'XV', 'BRZ', 'WRX'],
  'Suzuki': ['Jimny', 'Swift', 'Vitara', 'S-Cross', 'Baleno'],
  'Mazda': ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-30', 'CX-9', 'MX-5'],
  'Jaguar': ['XE', 'XF', 'XJ', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type'],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'RX', 'GX', 'LX'],
  'Ferrari': ['Roma', 'Portofino', 'SF90', 'F8', '812', '296', 'Purosangue'],
  'Lamborghini': ['Huracán', 'Urus', 'Aventador', 'Revuelto'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'Grecale'],
  'RAM': ['700', '1500', '2500', '3500'],
  'GWM': ['Haval H6', 'Haval H2', 'Ora Good Cat', 'Tank 300', 'Poer'],
  'JAC': ['J3', 'J5', 'J6', 'T40', 'T50', 'T60', 'T80', 'E-JS1'],
  'Chery': ['Tiggo 2', 'Tiggo 5x', 'Tiggo 7', 'Tiggo 8', 'Arrizo 6'],
  'Geely': ['Coolray', 'Geometry C', 'Emgrand'],
};

export const MOTORIZACOES_COMUNS = [
  '1.0',
  '1.0 Turbo',
  '1.0 TSI',
  '1.3',
  '1.4 Turbo',
  '1.4 TSI',
  '1.5',
  '1.5 Turbo',
  '1.6',
  '1.6 16V',
  '1.8',
  '1.8 Turbo',
  '2.0',
  '2.0 Turbo',
  '2.0 TSI',
  '2.0 TDI',
  '2.4',
  '2.5',
  '3.0',
  '3.0 Turbo',
  '3.5',
  '4.0',
  '4.2',
  '5.0',
  'Elétrico',
  'Híbrido',
];

export const MARCA_OUTRA = '__outra_marca__';
export const MODELO_OUTRO = '__outro__';
export const MOTORIZACAO_OUTRA = '__outra_motorizacao__';

export const MARCAS_NOMES = new Set(MARCAS_FIPE.map((m) => m.nome));
